### ISSUE TITLE
Add schema param to Postgis datasource

### ISSUE THREAD

**Issue by AndreaDiNora** [GeoSmartCity-CIP/gsc-datacatalogue#42]
We need to add also schema params in postgis datasource.

Verify the updated wiki.

**Comment by AndreaDiNora** [comment]
I see that on page the param is called Database name but json has schema param with his value.
So in page we need schema param, instead the request lack of database param.

**Comment by runarbe** [comment]
@AndreaDiNora I have added the database parameter - it has remained unchanged since the first version - at that time, schema was used as the database name... Sorry!

This requires an update both of gsc.js and the data catalogue I am afraid so you need to refresh both...

I will notify by e-mail when I have committed and merged this into the repo

**Comment by AndreaDiNora** [comment]
Data catalogue client is not updated on github.

**Comment by AndreaDiNora** [comment]
Done
