### ISSUE TITLE
List data source method requires iddatasource / datasourceId as input parameter

### ISSUE THREAD

**Issue by runarbe** [GeoSmartCity-CIP/gsc-datacatalogue#7]
@AndreaDiNora, @giannibarrotta This means a list request will only return exactly ONE record. This function needs to return all datasources for the logged in user and/or his organizations?

**Comment by Finrod56** [comment]
As you can see from the description of the service (section 7.4) 2 different types of research are performed, depending on the parameters provided in the request.
The first one only uses the record id as parameter. If so -since the id is a unique identifier- you will only get one record as you correctly pointed out.
Users can also perform a research by name. In this case they specify a portion of the datasource name (or the complete one), and optionally an organization id. This mode may return multiple results: all the datasources whose name was matched, and (if the org id parameter was provided) which belong to the given organization.

**Comment by runarbe** [comment]
@AndreaDiNora Excellent - I just used the parameters demonstrated on the test-page and couldn't see it there...

**Comment by Finrod56** [comment]
I must edit my previous comment: the second research type is done **by organization**. The datasource name will further refine the research but may be omitted.  (the other way around of what i previously wrote)

Besides that, it was impossible for us to use examples for two different test cases at the same time. 
You can try replace our example with one similar to this for the alternative usage:

{"organization":"1","datasourcename":"DS","detail":"true"}

where every datasource of the organization with id = 1 and name matching %DS% will be found
